version: 2

updates:
  - package-ecosystem: "npm"
    directories:
      - "packages/*"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
  - package-ecosystem: "nix"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
